name: Build my-resume

# Controls when the workflow will run
on:
  push:
    branches: 
      - master
    paths:
      - "src/v2/*"
      - ".github/workflows/my-resume.yml"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Latex Build
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src/v2
          root_file: main.tex

      - name: Rename Artifact
        run: mv src/v2/main.pdf Rishav_Resume.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        id: upload
        with:
          name: PDF
          path: Rishav_Resume.pdf
  
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        id: download
        with:
          name: PDF
          path: artifact

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          
      - name: Github Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.download.outputs.download-path }}/*
          tag_name: ${{ steps.vars.outputs.sha_short }}
          name: Release ${{ steps.vars.outputs.sha_short }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
