# This is a basic workflow to help you get started with Actions

name: Build my-resume

# Controls when the workflow will run
on:
  push:
    branches: 
      - master
    paths:
      - "my-resume/*"
      - ".github/workflows/my-resume.yml"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Latex Build
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: my-resume
          root_file: resume.tex
          extra_system_packages: "inkscape"
          latexmk_use_xelatex: true
#           extra_fonts: |
#             ./path/to/custom.ttf
#             ./fonts/*.otf

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        id: upload
        with:
          name: PDF
          path: my-resume/resume.pdf
  
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download Artifacts
        uses: actions/download-artifact@master
        id: download
        with:
          name: PDF
          path: artifact

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - run: |
          ls -l
          ls -l artifact/
          
      - name: Github Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.download.outputs.download-path }}/*
          tag_name: ${{ steps.vars.outputs.sha_short }}
          name: Release ${{ steps.vars.outputs.sha_short }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
